#[webserver]
#172.31.85.68 ansible_ssh_user='ec2-user'

[webservers]
172.31.89.68 ansible_ssh_user='ec2-user'
172.31.90.196 ansible_ssh_user='ubuntu'

#[db]
#172.31.22.142 ansible_ssh_user='ubuntu' 

#[lb]
#172.31.80.250 ansible_ssh_user='ubuntu'