[nfs]
172.31.30.100 ansible_ssh_user='ec2-user'

[webservers]
172.31.23.166 ansible_ssh_user='ec2-user'
172.31.19.116 ansible_ssh_user='ec2-user'

[db]
172.31.30.191 ansible_ssh_user='ec2-user' 

[lb]
172.31.83.81 ansible_ssh_user='ubuntu'