#[webserver]
#172.31.85.68 ansible_ssh_user='ec2-user'

[apache]
172.31.82.28 ansible_ssh_user='ec2-user'

[nginx]
172.31.85.53 ansible_ssh_user='ubuntu'

#[db]
#172.31.22.142 ansible_ssh_user='ubuntu' 

#[lb]
#172.31.80.250 ansible_ssh_user='ubuntu'